### PR TITLE
fix for intToBuffer method

### PR DESCRIPTION
**Pull request by vpulim**
Fix for https://github.com/ethjs/ethjs-util/issues/8

In the intToBuffer() method, we now call padToEven() on the hex string generated by intToHex() to ensure the new Buffer object  can parse the hex string correctly. 

NOTE: This fix is compatible with PR https://github.com/ethjs/ethjs-util/pull/7 and still maintains the fix for issue https://github.com/ethjs/ethjs-util/issues/6

### CODE REVIEW

**Comment by SilentCicero** [comment]
Will review, thanks!

**Comment by SilentCicero** [comment]
Can you describe where and how you are using this module, it would be helpful.

**Comment by vpulim** [comment]
@SilentCicero This module is used in ethereumjs-util to convert integers to Buffers (https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L170). Its also used in tests for ethereumjs-blockchain (https://github.com/ethereumjs/ethereumjs-blockchain/blob/master/test/index.js#L61).

However, simply calling intToBuffer() on ethjs-util fails when you pass in an integer < 16.

**Comment by SilentCicero** [comment]
This was due to the previous PR, okay, lets patch it then, thanks!

**Comment by vpulim** [comment]
Great! Thanks

**Comment by SilentCicero** [comment]
@vpulim should be up in NPM ethjs-util@0.1.6

**Pull request merged**
